### ISSUE TITLE
Handle and mouse misalign while dragging

### ISSUE THREAD

**Issue by jbalsas** [metal/crystal-slider#3]
While dragging the slider handle back and forth, the handle and the mouse misalign.

![slider](https://cloud.githubusercontent.com/assets/905006/9808687/cba78b06-5861-11e5-98e5-329372eb0932.gif)

**Comment by eduardolundgren** [comment]
Did you find the issue for the misalignment?

**Comment by jbalsas** [comment]
Hey Eduardo, I haven't had time to work on this.

However, I checked and this is the same behaviour as in the **constrain** demo in [metal-drag-drop](https://github.com/metal/metal-drag-drop), so we should probably fix it there.

![dragdrop](https://cloud.githubusercontent.com/assets/905006/10033455/ecb3b118-6189-11e5-8885-361147d58323.gif)

**Comment by mairatma** [comment]
Yep, I remember Eduardo mentioning this problem a while ago, and I myself noticed it the other day. The way the constrain functionality is working is causing us to keep moving the source even when the mouse is not on top of it anymore, but it really shouldn't.
I've created a bug on metal-drag-drop for this: https://github.com/metal/metal-drag-drop/issues/1.

**Comment by eduardolundgren** [comment]
We can close this one here in favor of https://github.com/metal/metal-drag-drop/issues/1.

**Comment by eduardolundgren** [comment]
Thanks!

**Comment by mairatma** [comment]
This should be working now after updating metal-drag-drop from bower :)
